<?php
/**
 * Plugin Name:       Play Audio once
 * Description:       Adds an option to the audio block to prevent the file from being played multiple times.
 * Requires at least: 5.8
 * Requires PHP:      8.0
 * Version:           @@VersionNumber@@
 * Author:            Thomas Zwirner
 * Author URI:        https://www.thomaszwirner.de
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       play-audio-once
 *
 * @package play-audio-once
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// do nothing if PHP-version is not 8.0 or newer.
if ( version_compare( PHP_VERSION, '8.0', '<' ) ) {
	return;
}

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

/**
 * Initialize the third party support.
 *
 * @return void
 */
function play_audio_once_init(): void {
	// initialize the third party support.
	\PlayAudioOnce\ThirdPartySupport::get_instance()->init();
}
add_action( 'init', 'play_audio_once_init' );

/**
 * Adds JavaScript-files to frontend.
 *
 * @return void
 * @noinspection PhpUnused
 */
function play_audio_once_scripts(): void {
	wp_register_script( 'play-audio-once-md5', plugins_url( 'libs/jquery.md5.js', __FILE__ ), array( 'jquery' ), filemtime( plugin_dir_path( __FILE__ ) . 'libs/jquery.md5.js' ), true );
	wp_enqueue_script( 'play-audio-once-md5' );
	wp_register_script( 'play-audio-once-frontend', plugins_url( 'js.js', __FILE__ ), array( 'jquery' ), filemtime( plugin_dir_path( __FILE__ ) . 'js.js' ), true );
	wp_enqueue_script( 'play-audio-once-frontend' );
}
add_action( 'wp_enqueue_scripts', 'play_audio_once_scripts' );

/**
 * Adds JavaScript-file for Gutenberg-editor to add the option.
 *
 * @return void
 * @noinspection PhpUnused
 */
function play_audio_once_assets(): void {
	wp_enqueue_script(
		'play-audio-once-backend-js',
		plugins_url( 'attributes/audioOption.js', __FILE__ ),
		array( 'wp-blocks', 'wp-element', 'wp-components', 'wp-i18n', 'wp-block-editor' ),
		filemtime( plugin_dir_path( __FILE__ ) . 'attributes/audioOption.js' ),
		true
	);
	if ( function_exists( 'wp_set_script_translations' ) ) {
		wp_set_script_translations(
			'play-audio-once-backend-js',
			'play-audio-once',
			trailingslashit( plugin_dir_path( __FILE__ ) ) . 'languages/'
		);
	}
}
add_action( 'enqueue_block_assets', 'play_audio_once_assets' );
