<?php
/**
 * Plugin Name:       Play Audio once
 * Description:       Adds an option to the audio block to prevent the file from being played multiple times.
 * Requires at least: 5.8
 * Requires PHP:      8.0
 * Version:           @@VersionNumber@@
 * Author:            Thomas Zwirner
 * Author URI:        https://www.thomaszwirner.de
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       play-audio-once
 *
 * @package play-audio-once
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// do nothing if PHP-version is not 8.0 or newer.
if ( PHP_VERSION_ID < 80000 ) { // @phpstan-ignore smaller.alwaysFalse
	return;
}

use PlayAudioOnce\Settings;
use PlayAudioOnce\ThirdPartySupport;

// save the plugin path.
const PLAO_PLUGIN = __FILE__;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

/**
 * Initialize the third party support.
 *
 * @return void
 */
function play_audio_once_init(): void {
	// initialize the settings.
	Settings::get_instance()->add_settings();

	// initialize the third party support.
	ThirdPartySupport::get_instance()->init();
}
add_action( 'init', 'play_audio_once_init' );

/**
 * Adds JavaScript-files to frontend.
 *
 * @return void
 * @noinspection PhpUnused
 */
function play_audio_once_scripts(): void {
	wp_register_script( 'play-audio-once-md5', plugins_url( 'libs/jquery.md5.js', __FILE__ ), array( 'jquery' ), (string) filemtime( plugin_dir_path( __FILE__ ) . 'libs/jquery.md5.js' ), true );
	wp_enqueue_script( 'play-audio-once-md5' );
	wp_register_script( 'play-audio-once-frontend', plugins_url( 'js.js', __FILE__ ), array( 'jquery' ), (string) filemtime( plugin_dir_path( __FILE__ ) . 'js.js' ), true );
	wp_enqueue_script( 'play-audio-once-frontend' );
}
add_action( 'wp_enqueue_scripts', 'play_audio_once_scripts' );

/**
 * Adds JavaScript-file for Gutenberg-editor to add the option.
 *
 * @return void
 * @noinspection PhpUnused
 */
function play_audio_once_assets(): void {
	wp_enqueue_script(
		'play-audio-once-backend-js',
		plugins_url( 'attributes/audioOption.js', __FILE__ ),
		array( 'wp-blocks', 'wp-element', 'wp-components', 'wp-i18n', 'wp-block-editor' ),
		(string) filemtime( plugin_dir_path( __FILE__ ) . 'attributes/audioOption.js' ),
		true
	);
	if ( function_exists( 'wp_set_script_translations' ) ) {
		wp_set_script_translations(
			'play-audio-once-backend-js',
			'play-audio-once',
			trailingslashit( plugin_dir_path( __FILE__ ) ) . 'languages/'
		);
	}
}
add_action( 'enqueue_block_assets', 'play_audio_once_assets' );

/**
 * Add links in row meta.
 *
 * @param array<string> $links List of links.
 * @param string        $file The requested plugin file name.
 *
 * @return array<string>
 */
function play_audio_once_add_row_meta_links( array $links, string $file ): array {
	// bail if this is not our plugin.
	if ( __FILE__ !== WP_PLUGIN_DIR . DIRECTORY_SEPARATOR . $file ) {
		return $links;
	}

	// add our custom links.
	$row_meta = array(
		'support' => '<a href="https://wordpress.org/support/plugin/play-audio-once/" target="_blank" title="' . esc_attr__( 'Support Forum', 'play-audio-once' ) . '">' . esc_html__( 'Support Forum', 'play-audio-once' ) . '</a>',
	);

	// return the resulting list of links.
	return array_merge( $links, $row_meta );
}
add_filter( 'plugin_row_meta', 'play_audio_once_add_row_meta_links', 10, 2 );

/**
 * Add links in plugin list.
 *
 * @param array<string> $links List of links on plugin in plugin list.
 *
 * @return array<string>
 */
function play_audio_once_add_setting_link( array $links ): array {
	// add the link to the list.
	$links[] = '<a href="' . esc_url( \PlayAudioOnce\Dependencies\easySettingsForWordPress\Settings::get_instance()->get_settings_link() ) . '">' . esc_html__( 'Settings', 'play-audio-once' ) . '</a>';

	// get language-dependent URL for the how-to.
	$url = 'https://github.com/threadi/play-audio-once/blob/master/docs/how_to_use.md';
	if ( str_starts_with( get_locale(), 'de_' ) ) {
		$url = 'https://github.com/threadi/play-audio-once/blob/master/docs/how_to_use_de.md';
	}

	// add the link to the list.
	$links[] = '<a href="' . esc_url( $url ) . '" target="_blank">' . esc_html__( 'How to use', 'play-audio-once' ) . '</a>';

	// return resulting list of links.
	return $links;
}
add_filter( 'plugin_action_links_' . plugin_basename( __FILE__ ), 'play_audio_once_add_setting_link' );

/**
 * Add css class on body to prevent audio play multiple times in complete website.
 *
 * @param array<string> $css_classes List of body classes.
 * @return array<string>
 */
function play_audio_once_add_body_classes( array $css_classes ): array {
	// bail if setting is not enabled.
	if ( 1 !== absint( get_option( 'play_audio_once_whole_site' ) ) ) {
		return $css_classes;
	}

	// add our class to the list.
	$css_classes[] = 'audio-play-once-true';

	// return the resulting list.
	return $css_classes;
}
add_filter( 'body_class', 'play_audio_once_add_body_classes' );
